You can't installl eyed3 on PyPy.
There is error during installation:

  Downloading eyeD3-0.7.9.tar.gz (230kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "app_main.py", line 581, in run_it
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-jXtj27/eyed3/setup.py", line 10, in <module>
        paver.tasks.main()
      File "paver-minilib.zip/paver/tasks.py", line 878, in main
        _launch_pavement(args)
      File "paver-minilib.zip/paver/tasks.py", line 846, in _launch_pavement
        exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
      File "pavement.py", line 462, in <module>
        __builtins__["cog_pluginHelp"] = cog_pluginHelp
    TypeError: 'module' object does not support item assignment

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jXtj27/eyed3